name: DEV CI

on:
  push:
    branches:
      - 'features/**'
      - 'hotfixes/**'
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HERE_API_KEY: ${{ secrets.HERE_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: test
        run: mvn -B clean test
      - name: integration tests
        if: github.event.pull_request.base.ref == 'main'
        run: mvn -B clean integration-test
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build docker Image
        run: